### 1- Find record if Sales greater than 500 and Quantity greater than 5?

In [14]:
import pandas as pd

df = pd.read_csv("retail supermarket.csv")

fil_df = df[(df['Sales'] > 500 ) & (df['Quantity'] > 5 )]
        

fil_df

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
7,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Technology,Phones,907.152,6.0,0.2,90.7152,NaN,NaN
10,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Furniture,Tables,1706.184,9.0,0.2,85.3092,NaN,NaN
16,Standard Class,Consumer,United States,Madison,Wisconsin,53711.0,Central,Office Supplies,Storage,665.880,6.0,0.0,13.3176,NaN,NaN
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Furniture,Bookcases,3083.430,7.0,0.5,-1665.0522,NaN,NaN
35,First Class,Corporate,United States,Richardson,Texas,75080.0,Central,Technology,Phones,1097.544,7.0,0.2,123.4737,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9879,Standard Class,Consumer,United States,New York City,New York,10035.0,East,Furniture,Chairs,573.174,7.0,0.1,63.6860,NaN,NaN
9925,First Class,Corporate,United States,New York City,New York,10035.0,East,Office Supplies,Binders,1087.936,8.0,0.2,353.5792,NaN,NaN
9942,Standard Class,Consumer,United States,Anaheim,California,92804.0,West,Office Supplies,Storage,998.820,9.0,0.0,29.9646,NaN,NaN
9947,Second Class,Corporate,United States,Indianapolis,Indiana,46203.0,Central,Furniture,Chairs,1925.880,6.0,0.0,539.2464,NaN,NaN
9948,Second Class,Corporate,United States,Indianapolis,Indiana,46203.0,Central,Office Supplies,Appliances,2405.200,8.0,0.0,793.7160,NaN,NaN

### 2- Find records if Discount is more than 0.5 (50%) or Profit is negative.

In [17]:
df1 = df[(df['Discount'] > 0.50 ) | (df['Profit'] < 0 )]
df1

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Furniture,Tables,957.5775,5.0,0.45,-383.0310,NaN,NaN
14,Standard Class,Home Office,United States,Fort Worth,Texas,76106.0,Central,Office Supplies,Appliances,68.8100,5.0,0.80,-123.8580,NaN,NaN
15,Standard Class,Home Office,United States,Fort Worth,Texas,76106.0,Central,Office Supplies,Binders,2.5440,3.0,0.80,-3.8160,NaN,NaN
23,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Furniture,Chairs,71.3720,2.0,0.30,-1.0196,NaN,NaN
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Furniture,Bookcases,3083.4300,7.0,0.50,-1665.0522,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9920,Standard Class,Corporate,United States,Bryan,Texas,77803.0,Central,Office Supplies,Binders,22.3860,7.0,0.80,-35.8176,NaN,NaN
9921,Standard Class,Home Office,United States,Akron,Ohio,44312.0,East,Office Supplies,Binders,5.7420,3.0,0.70,-4.5936,NaN,NaN
9931,Standard Class,Consumer,United States,San Bernardino,California,92404.0,West,Furniture,Bookcases,683.3320,4.0,0.15,-40.1960,NaN,NaN
9937,Second Class,Corporate,United States,Los Angeles,California,90049.0,West,Furniture,Tables,71.0880,2.0,0.20,-1.7772,NaN,NaN
9962,First Class,Home Office,United States,Houston,Texas,77041.0,Central,Furniture,Bookcases,383.4656,4.0,0.32,-67.6704,NaN,NaN

### 3- Display Ship Mode and Profit columns if region is East using loc

In [19]:
east_df = df.loc[df['Region'] == 'East', ['Ship Mode', 'Profit','Region']]
east_df

           Ship Mode     Profit Region
23      Second Class    -1.0196   East
27    Standard Class -1665.0522   East
28    Standard Class    -7.0532   East
29    Standard Class    15.5250   East
30    Standard Class     1.1016   East
...              ...        ...    ...
9968  Standard Class   331.1910   East
9969  Standard Class     6.5975   East
9981     First Class     5.3690   East
9984  Standard Class    15.1200   East
9985  Standard Class    16.1240   East

[2848 rows x 3 columns]

### 4- How many records belong to the "Corporate" segment and the "Central" region?

In [24]:
count = len(df[(df['Segment'] == 'Corporate') & (df['Region'] == 'Central')])

count

673

### 5- Find all orders in the "Furniture" category but not in "Chairs" sub-category.

In [27]:
f_df = df[(df['Category'] == 'Furniture') & (df['Sub-Category'] != 'Chairs')]
f_df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
0,Second Class,Consumer,United States,Henderson,Kentucky,42420.0,South,Furniture,Bookcases,261.9600,2.0,0.00,41.9136,NaN,NaN
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Furniture,Tables,957.5775,5.0,0.45,-383.0310,NaN,NaN
5,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Furniture,Furnishings,48.8600,7.0,0.00,14.1694,NaN,NaN
10,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Furniture,Tables,1706.1840,9.0,0.20,85.3092,NaN,NaN
24,Standard Class,Consumer,United States,Orem,Utah,84057.0,West,Furniture,Tables,1044.6300,3.0,0.00,240.2649,NaN,NaN

### 6- Which orders have discount (>0.3) and still earned profit (>0)?

In [29]:
d_df = df[(df['Discount'] > 0.3) & (df['Profit'] > 0)]
d_df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
343,Second Class,Corporate,United States,Philadelphia,Pennsylvania,19140.0,East,Technology,Phones,71.928,12.0,0.4,8.3916,NaN,NaN
614,Second Class,Consumer,United States,Grove City,Ohio,43123.0,East,Technology,Phones,119.940,10.0,0.4,15.9920,NaN,NaN
986,Standard Class,Home Office,United States,Pasadena,Texas,77506.0,Central,Technology,Machines,336.510,3.0,0.4,44.8680,NaN,NaN
1233,First Class,Corporate,United States,Cincinnati,Ohio,45231.0,East,Technology,Copiers,839.988,2.0,0.4,69.9990,NaN,NaN
1679,Standard Class,Corporate,United States,Philadelphia,Pennsylvania,19134.0,East,Technology,Phones,32.382,3.0,0.4,4.3176,NaN,NaN

### 7- Find high-profit orders where Quantity > 5 and Category == 'Technology'.

In [32]:
t_df = df[(df['Quantity'] > 5) & 
                        (df['Category'] == 'Technology') & 
                        (df['Profit'] > 1000)]
t_df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
1085,Standard Class,Consumer,United States,Yonkers,New York,10701.0,East,Technology,Machines,4899.930,7.0,0.0,2400.9657,NaN,NaN
1454,First Class,Corporate,United States,Mobile,Alabama,36608.0,South,Technology,Machines,3040.000,8.0,0.0,1459.2000,NaN,NaN
1644,First Class,Corporate,United States,Seattle,Washington,98115.0,West,Technology,Copiers,3149.930,7.0,0.0,1480.4671,NaN,NaN
2492,Standard Class,Consumer,United States,Jamestown,New York,14701.0,East,Technology,Phones,4548.810,7.0,0.0,1228.1787,NaN,NaN
3273,Standard Class,Home Office,United States,Los Angeles,California,90032.0,West,Technology,Copiers,3359.952,6.0,0.2,1049.9850,NaN,NaN

### 8- Select rows 0–4 and columns 'Ship Mode', 'Segment', 'Sales' by position using iloc

In [33]:
subset = df.iloc[0:5, [0, 1, 9]]
subset

        Ship Mode    Segment     Sales
0    Second Class   Consumer  261.9600
1    Second Class   Consumer  731.9400
2    Second Class  Corporate   14.6200
3  Standard Class   Consumer  957.5775
4  Standard Class   Consumer   22.3680

### 9- Show Home Office segment orders with Sales > 1000 and Quantity > 3.

In [35]:
o_df = df[(df['Segment'] == 'Home Office') & (df['Sales'] > 1000) & (df['Quantity'] > 3)]
o_df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
244,Second Class,Home Office,United States,Lakeville,Minnesota,55044.0,Central,Furniture,Chairs,2001.860,7.0,0.0,580.5394,NaN,NaN
247,Second Class,Home Office,United States,Lakeville,Minnesota,55044.0,Central,Office Supplies,Appliances,1503.250,5.0,0.0,496.0725,NaN,NaN
353,First Class,Home Office,United States,New York City,New York,10009.0,East,Office Supplies,Binders,4355.168,4.0,0.2,1415.4296,NaN,NaN
463,Standard Class,Home Office,United States,Phoenix,Arizona,85023.0,West,Furniture,Tables,1272.630,6.0,0.5,-814.4832,NaN,NaN
515,Standard Class,Home Office,United States,Great Falls,Montana,59405.0,West,Technology,Copiers,2999.950,5.0,0.0,1379.9770,NaN,NaN

### 10- Find orders where Profit Margin > 0.3

Profit Margin = (Profit/Sales)

In [39]:
df['Profit Margin'] = df['Profit'] / df['Sales']
pf =  df[df['Profit Margin'] > 0.3]
pf.head(10)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14,Profit Margin
2,Second Class,Corporate,United States,Los Angeles,California,90036.0,West,Office Supplies,Labels,14.620,2.0,0.0,6.8714,NaN,NaN,0.4700
8,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Office Supplies,Binders,18.504,3.0,0.2,5.7825,NaN,NaN,0.3125
12,Standard Class,Consumer,United States,Concord,North Carolina,28027.0,South,Office Supplies,Paper,15.552,3.0,0.2,5.4432,NaN,NaN,0.3500
13,Standard Class,Consumer,United States,Seattle,Washington,98103.0,West,Office Supplies,Binders,407.976,3.0,0.2,132.5922,NaN,NaN,0.3250
20,Second Class,Consumer,United States,San Francisco,California,94109.0,West,Office Supplies,Binders,22.720,4.0,0.2,7.3840,NaN,NaN,0.3250
25,Second Class,Consumer,United States,Los Angeles,California,90049.0,West,Office Supplies,Binders,11.648,2.0,0.2,4.2224,NaN,NaN,0.3625
30,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Office Supplies,Envelopes,3.264,2.0,0.2,1.1016,NaN,NaN,0.3375
34,Second Class,Home Office,United States,Houston,Texas,77095.0,Central,Office Supplies,Paper,29.472,3.0,0.2,9.9468,NaN,NaN,0.3375
37,Standard Class,Home Office,United States,Houston,Texas,77041.0,Central,Office Supplies,Envelopes,113.328,9.0,0.2,35.4150,NaN,NaN,0.3125
44,First Class,Corporate,United States,Eagan,Minnesota,55122.0,Central,Technology,Accessories,45.980,2.0,0.0,19.7714,NaN,NaN,0.4300

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ship Mode      9994 non-null   object
 1   Segment        9994 non-null   object
 2   Country        9994 non-null   object
 3   City           9994 non-null   object
 4   State          9994 non-null   object
 5   Postal Code    9994 non-null   float64
 6   Region         9994 non-null   object
 7   Category       9994 non-null   object
 8   Sub-Category   9994 non-null   object
 9   Sales          9994 non-null   float64
 10  Quantity       9994 non-null   float64
 11  Discount       9994 non-null   float64
 12  Profit         9994 non-null   float64
 13  Unnamed: 13    0 non-null      float64
 14  Unnamed: 14    0 non-null      float64
 15  Profit Margin  9994 non-null   float64
dtypes: float64(8), object(8)
memory usage: 1.2+ MB