### 1- Find record if Sales greater than 500 and Quantity greater than 5?

In [4]:
import pandas as pd

df = pd.read_csv("retail supermarket.csv")

df1 = df[(df['Sales'] > 500 )  & (df['Quantity'] > 5 )]  # why itny brackets or tuples
df1.head(5)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
7,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Technology,Phones,907.152,6.0,0.2,90.7152,NaN,NaN
10,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Furniture,Tables,1706.184,9.0,0.2,85.3092,NaN,NaN
16,Standard Class,Consumer,United States,Madison,Wisconsin,53711.0,Central,Office Supplies,Storage,665.880,6.0,0.0,13.3176,NaN,NaN
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Furniture,Bookcases,3083.430,7.0,0.5,-1665.0522,NaN,NaN
35,First Class,Corporate,United States,Richardson,Texas,75080.0,Central,Technology,Phones,1097.544,7.0,0.2,123.4737,NaN,NaN

### 2- Find records if Discount is more than 0.5 (50%) or Profit is negative.

In [45]:
df2 = df[(df['Discount'] >0.5 ) & (df['Profit'] < 0.0 ) ]
df2.head(8)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
14,Standard Class,Home Office,United States,Fort Worth,Texas,76106.0,Central,Office Supplies,Appliances,68.810,5.0,0.8,-123.8580,NaN,NaN
15,Standard Class,Home Office,United States,Fort Worth,Texas,76106.0,Central,Office Supplies,Binders,2.544,3.0,0.8,-3.8160,NaN,NaN
28,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Office Supplies,Binders,9.618,2.0,0.7,-7.0532,NaN,NaN
32,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Office Supplies,Binders,6.858,6.0,0.7,-5.7150,NaN,NaN
36,First Class,Corporate,United States,Richardson,Texas,75080.0,Central,Furniture,Furnishings,190.920,5.0,0.6,-147.9630,NaN,NaN
75,First Class,Corporate,United States,Houston,Texas,77041.0,Central,Office Supplies,Binders,1.248,3.0,0.8,-1.9344,NaN,NaN
76,First Class,Corporate,United States,Houston,Texas,77041.0,Central,Furniture,Furnishings,9.708,3.0,0.6,-5.8248,NaN,NaN
78,Second Class,Consumer,United States,Houston,Texas,77070.0,Central,Furniture,Furnishings,19.300,5.0,0.6,-14.4750,NaN,NaN

### 3- Display Ship Mode and Profit columns if region is East using loc

In [57]:
df3 = df.loc[df['Region'] == 'East' , ['Ship Mode','Profit','Region']]
df3.head(10)

         Ship Mode     Profit Region
23    Second Class    -1.0196   East
27  Standard Class -1665.0522   East
28  Standard Class    -7.0532   East
29  Standard Class    15.5250   East
30  Standard Class     1.1016   East
31  Standard Class     9.7092   East
32  Standard Class    -5.7150   East
33  Standard Class     3.5460   East
47  Standard Class     4.9500   East
48  Standard Class     6.1040   East

### 4- How many records belong to the "Corporate" segment and the "Central" region?

In [4]:
count = len(df[(df['Segment'] == 'Corporate') & (df['Region'] == 'Central')])

count

673

In [7]:
df4 = len(df[(df['Segment'] == 'Corporate')  & (df['Region'] == 'Central')])
df4

673

### 5- Find all orders in the "Furniture" category but not in "Chairs" sub-category.

In [9]:
df5 = (df[(df['Category'] == 'Furniture' ) & (df['Sub-Category'] != 'Chairs')])
df5.head(10)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
0,Second Class,Consumer,United States,Henderson,Kentucky,42420.0,South,Furniture,Bookcases,261.9600,2.0,0.00,41.9136,NaN,NaN
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Furniture,Tables,957.5775,5.0,0.45,-383.0310,NaN,NaN
5,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Furniture,Furnishings,48.8600,7.0,0.00,14.1694,NaN,NaN
10,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Furniture,Tables,1706.1840,9.0,0.20,85.3092,NaN,NaN
24,Standard Class,Consumer,United States,Orem,Utah,84057.0,West,Furniture,Tables,1044.6300,3.0,0.00,240.2649,NaN,NaN
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Furniture,Bookcases,3083.4300,7.0,0.50,-1665.0522,NaN,NaN
29,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,Furniture,Furnishings,124.2000,3.0,0.20,15.5250,NaN,NaN
36,First Class,Corporate,United States,Richardson,Texas,75080.0,Central,Furniture,Furnishings,190.9200,5.0,0.60,-147.9630,NaN,NaN
38,Standard Class,Home Office,United States,Houston,Texas,77041.0,Central,Furniture,Bookcases,532.3992,3.0,0.32,-46.9764,NaN,NaN
51,Standard Class,Consumer,United States,New Albany,Indiana,47150.0,Central,Furniture,Furnishings,6.1600,2.0,0.00,2.9568,NaN,NaN

### 6- Which orders have discount (>0.3) and still earned profit (>0)?

In [ ]:
df6 = (df[(df['Discount'] > 0.3 ) & (df['Profit'] > 50 )]) #mx disc kitna diya he 
df6.head(27) #how find sales and profit then exp how much

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
1233,First Class,Corporate,United States,Cincinnati,Ohio,45231.0,East,Technology,Copiers,839.988,2.0,0.4,69.9990,NaN,NaN
1986,First Class,Consumer,United States,Columbus,Ohio,43229.0,East,Technology,Copiers,1439.976,4.0,0.4,191.9968,NaN,NaN
2728,First Class,Consumer,United States,Toledo,Ohio,43615.0,East,Technology,Phones,629.958,7.0,0.4,94.4937,NaN,NaN
4491,Second Class,Consumer,United States,Columbus,Ohio,43229.0,East,Technology,Copiers,659.988,2.0,0.4,109.9980,NaN,NaN
4812,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19134.0,East,Technology,Copiers,1199.976,4.0,0.4,179.9964,NaN,NaN
5385,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19143.0,East,Technology,Phones,545.916,14.0,0.4,72.7888,NaN,NaN
6425,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,Technology,Copiers,8399.976,4.0,0.4,1119.9968,NaN,NaN
6951,Standard Class,Corporate,United States,Dallas,Texas,75217.0,Central,Technology,Machines,479.988,2.0,0.4,55.9986,NaN,NaN
7042,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134.0,East,Technology,Copiers,599.970,5.0,0.4,69.9965,NaN,NaN
8123,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134.0,East,Technology,Copiers,1079.976,4.0,0.4,125.9972,NaN,NaN
8799,First Class,Consumer,United States,Philadelphia,Pennsylvania,19134.0,East,Technology,Copiers,1799.970,5.0,0.4,239.9960,NaN,NaN
9617,Standard Class,Corporate,United States,Bowling Green,Ohio,43402.0,East,Technology,Copiers,899.982,3.0,0.4,74.9985,NaN,NaN

### 7- Find high-profit orders where Quantity > 5 and Category == 'Technology'.

In [46]:
df7 = df[(df['Quantity'] > 5 ) & (df['Category'] == 'Technology ') & (df['Profit'] > 1000 )]
df7.head(5)

Empty DataFrame
Columns: [Ship Mode, Segment, Country, City, State, Postal Code, Region, Category, Sub-Category, Sales, Quantity, Discount, Profit, Unnamed: 13, Unnamed: 14, Sales_minus_Profit_%, Profit_in_Sales_%, Expense_%_of_Sales, sales%_in_sales, Profit_Percentage, Expense_Percentage]
Index: []

[0 rows x 21 columns]

In [54]:
high_profit_orders = df[(df['Quantity'] > 5) & 
                        (df['Category'] == 'Technology') & 
                        (df['Profit'] > 1000)]

high_profit_orders.head(10)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14,Profit_in_Sales_%,sales%_in_sales,Profit_Percentage,Expense_Percentage
1085,Standard Class,Consumer,United States,Yonkers,New York,10701.0,East,Technology,Machines,4899.930,7.0,0.0,2400.9657,NaN,NaN,49.00,51.00,49.00,51.00
1454,First Class,Corporate,United States,Mobile,Alabama,36608.0,South,Technology,Machines,3040.000,8.0,0.0,1459.2000,NaN,NaN,48.00,52.00,48.00,52.00
1644,First Class,Corporate,United States,Seattle,Washington,98115.0,West,Technology,Copiers,3149.930,7.0,0.0,1480.4671,NaN,NaN,47.00,53.00,47.00,53.00
2492,Standard Class,Consumer,United States,Jamestown,New York,14701.0,East,Technology,Phones,4548.810,7.0,0.0,1228.1787,NaN,NaN,27.00,73.00,27.00,73.00
3273,Standard Class,Home Office,United States,Los Angeles,California,90032.0,West,Technology,Copiers,3359.952,6.0,0.2,1049.9850,NaN,NaN,31.25,68.75,31.25,68.75
4093,Standard Class,Consumer,United States,Florence,Kentucky,41042.0,South,Technology,Machines,3080.000,7.0,0.0,1416.8000,NaN,NaN,46.00,54.00,46.00,54.00
4277,Standard Class,Corporate,United States,Lakewood,New Jersey,8701.0,East,Technology,Machines,9099.930,7.0,0.0,2365.9818,NaN,NaN,26.00,74.00,26.00,74.00
4619,First Class,Home Office,United States,Los Angeles,California,90049.0,West,Technology,Copiers,2879.952,6.0,0.2,1007.9832,NaN,NaN,35.00,65.00,35.00,65.00
5710,Standard Class,Consumer,United States,New York City,New York,10024.0,East,Technology,Copiers,2799.944,7.0,0.2,1014.9797,NaN,NaN,36.25,63.75,36.25,63.75
7666,Standard Class,Home Office,United States,Providence,Rhode Island,2908.0,East,Technology,Copiers,5399.910,9.0,0.0,2591.9568,NaN,NaN,48.00,52.00,48.00,52.00

In [50]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,...,Discount,Profit,Unnamed: 13,Unnamed: 14,Sales_minus_Profit_%,Profit_in_Sales_%,Expense_%_of_Sales,sales%_in_sales,Profit_Percentage,Expense_Percentage
0,Second Class,Consumer,United States,Henderson,Kentucky,42420.0,South,Furniture,Bookcases,261.9600,...,0.00,41.9136,NaN,NaN,84.00,16.00,84.00,84.00,16.00,84.00
1,Second Class,Consumer,United States,Henderson,Kentucky,42420.0,South,Furniture,Chairs,731.9400,...,0.00,219.5820,NaN,NaN,70.00,30.00,70.00,70.00,30.00,70.00
2,Second Class,Corporate,United States,Los Angeles,California,90036.0,West,Office Supplies,Labels,14.6200,...,0.00,6.8714,NaN,NaN,53.00,47.00,53.00,53.00,47.00,53.00
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Furniture,Tables,957.5775,...,0.45,-383.0310,NaN,NaN,140.00,-40.00,140.00,140.00,-40.00,140.00
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Office Supplies,Storage,22.3680,...,0.20,2.5164,NaN,NaN,88.75,11.25,88.75,88.75,11.25,88.75

In [24]:
print(df['Profit'].describe())
print(df['Sales'].describe())
print(df['Discount'].describe())

count    9994.000000
mean       28.656896
std       234.260108
min     -6599.978000
25%         1.728750
50%         8.666500
75%        29.364000
max      8399.976000
Name: Profit, dtype: float64
count     9994.000000
mean       229.858001
std        623.245101
min          0.444000
25%         17.280000
50%         54.490000
75%        209.940000
max      22638.480000
Name: Sales, dtype: float64
count    9994.000000
mean        0.156203
std         0.206452
min         0.000000
25%         0.000000
50%         0.200000
75%         0.200000
max         0.800000
Name: Discount, dtype: float64

In [ ]:
df['Profit_Percentage'] = (df['Profit'] / df['Sales']) * 100
df['Expense_Percentage'] = ((df['Sales'] - df['Profit']) / df['Sales']) * 100

display(df[['Sales','Profit','Profit_Percentage','Expense_Percentage']].head(10))

      Sales    Profit  Profit_Percentage  Expense_Percentage
0  261.9600   41.9136              16.00               84.00
1  731.9400  219.5820              30.00               70.00
2   14.6200    6.8714              47.00               53.00
3  957.5775 -383.0310             -40.00              140.00
4   22.3680    2.5164              11.25               88.75
5   48.8600   14.1694              29.00               71.00
6    7.2800    1.9656              27.00               73.00
7  907.1520   90.7152              10.00               90.00
8   18.5040    5.7825              31.25               68.75
9  114.9000   34.4700              30.00               70.00

### 8- Select rows 0–4 and columns 'Ship Mode', 'Segment', 'Sales' by position using iloc

In [5]:
df8 = df.iloc[0:5 , [0,1,4]]
df8

        Ship Mode    Segment       State
0    Second Class   Consumer    Kentucky
1    Second Class   Consumer    Kentucky
2    Second Class  Corporate  California
3  Standard Class   Consumer     Florida
4  Standard Class   Consumer     Florida

### 9- Show Home Office segment orders with Sales > 1000 and Quantity > 3.

In [ ]:
o_df = df[(df['Segment'] == 'Home Office') & (df['Sales'] > 1000) & (df['Quantity'] > 3)]
o_df.head()

In [18]:
df9 = (df[(df['Segment'] == 'Home Office') & (df['Sales'] > 1000 ) & (df['Quantity'] > 3 )])
df9.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14
244,Second Class,Home Office,United States,Lakeville,Minnesota,55044.0,Central,Furniture,Chairs,2001.860,7.0,0.0,580.5394,NaN,NaN
247,Second Class,Home Office,United States,Lakeville,Minnesota,55044.0,Central,Office Supplies,Appliances,1503.250,5.0,0.0,496.0725,NaN,NaN
353,First Class,Home Office,United States,New York City,New York,10009.0,East,Office Supplies,Binders,4355.168,4.0,0.2,1415.4296,NaN,NaN
463,Standard Class,Home Office,United States,Phoenix,Arizona,85023.0,West,Furniture,Tables,1272.630,6.0,0.5,-814.4832,NaN,NaN
515,Standard Class,Home Office,United States,Great Falls,Montana,59405.0,West,Technology,Copiers,2999.950,5.0,0.0,1379.9770,NaN,NaN

### 10- Find orders where Profit Margin > 0.3

Profit Margin = (Profit/Sales)

In [20]:
df['Profit Margin'] = df['Profit'] / df['Sales'] * 100
df10 = df[df['Profit Margin'] > 0.3]
df10.head(10)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Unnamed: 13,Unnamed: 14,Profit Margin
0,Second Class,Consumer,United States,Henderson,Kentucky,42420.0,South,Furniture,Bookcases,261.960,2.0,0.0,41.9136,NaN,NaN,16.00
1,Second Class,Consumer,United States,Henderson,Kentucky,42420.0,South,Furniture,Chairs,731.940,3.0,0.0,219.5820,NaN,NaN,30.00
2,Second Class,Corporate,United States,Los Angeles,California,90036.0,West,Office Supplies,Labels,14.620,2.0,0.0,6.8714,NaN,NaN,47.00
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Office Supplies,Storage,22.368,2.0,0.2,2.5164,NaN,NaN,11.25
5,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Furniture,Furnishings,48.860,7.0,0.0,14.1694,NaN,NaN,29.00
6,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Office Supplies,Art,7.280,4.0,0.0,1.9656,NaN,NaN,27.00
7,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Technology,Phones,907.152,6.0,0.2,90.7152,NaN,NaN,10.00
8,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Office Supplies,Binders,18.504,3.0,0.2,5.7825,NaN,NaN,31.25
9,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Office Supplies,Appliances,114.900,5.0,0.0,34.4700,NaN,NaN,30.00
10,Standard Class,Consumer,United States,Los Angeles,California,90032.0,West,Furniture,Tables,1706.184,9.0,0.2,85.3092,NaN,NaN,5.00

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ship Mode      9994 non-null   object
 1   Segment        9994 non-null   object
 2   Country        9994 non-null   object
 3   City           9994 non-null   object
 4   State          9994 non-null   object
 5   Postal Code    9994 non-null   float64
 6   Region         9994 non-null   object
 7   Category       9994 non-null   object
 8   Sub-Category   9994 non-null   object
 9   Sales          9994 non-null   float64
 10  Quantity       9994 non-null   float64
 11  Discount       9994 non-null   float64
 12  Profit         9994 non-null   float64
 13  Unnamed: 13    0 non-null      float64
 14  Unnamed: 14    0 non-null      float64
 15  Profit Margin  9994 non-null   float64
dtypes: float64(8), object(8)
memory usage: 1.2+ MB