In [9]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('Salaries.csv')
df.drop(['Id'], axis=1, inplace=True)
df.tail(15)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148639,Richard A Talbert,Custodian,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148640,Charlene D Mccully,Parking Control Officer,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148641,Raphael Marquis Goins,Museum Guard,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148642,Dominic C Marquez,Sign Worker,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148643,Kim Brewer,Parking Control Officer,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148644,Randy D Winn,"Stationary Eng, Sewage Plant",0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148645,Carolyn A Wilson,Human Services Technician,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148646,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,Joann Anderson,Communications Dispatcher 2,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148648,Leon Walker,Custodian,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148649,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,NaN,San Francisco,PT
148650,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,NaN,San Francisco,PT

Drop rows where EmployeeName and JobTitle are 'Not provided'

In [7]:
df.shape

(148654, 12)

In [14]:
df = df[(df['EmployeeName'].str.lower() != 'Not provided') & (df['JobTitle'].str.lower() != 'Not provided')]

df.shape

(148650, 12)

In [24]:
df.iloc[100:115]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
100,KEVIN TAYLOR,"BATTALION CHIEF, (FIRE DEPARTMENT)",168692.65,33656.87,21502.83,NaN,223852.35,223852.35,2011,NaN,San Francisco,NaN
101,ERIKA HOO,"LIEUTENANT, FIRE DEPARTMENT",123105.0,84547.16,16054.24,NaN,223706.40,223706.40,2011,NaN,San Francisco,NaN
102,LAUIFI SEUMAALA,FIREFIGHTER,105934.69,98534.35,18890.96,NaN,223360.00,223360.00,2011,NaN,San Francisco,NaN
103,EDWARD DENNIS,TRANSIT SUPERVISOR,88400.7,126778.88,7228.67,NaN,222408.25,222408.25,2011,NaN,San Francisco,NaN
104,PATRIC STEELE,FIREFIGHTER,105934.64,97395.59,18760.77,NaN,222091.00,222091.00,2011,NaN,San Francisco,NaN
105,MICHAEL WALSH,FIREFIGHTER,110474.93,83670.04,27043.61,NaN,221188.58,221188.58,2011,NaN,San Francisco,NaN
106,SAMSON LAI,"BATTALION CHIEF, (FIRE DEPARTMENT)",149362.86,35003.5,36682.96,NaN,221049.32,221049.32,2011,NaN,San Francisco,NaN
107,ANA SAMPERA,NURSING SUPERVISOR,188708.0,0.0,32080.36,NaN,220788.36,220788.36,2011,NaN,San Francisco,NaN
108,GLORIA GARCIA ORME,NURSING SUPERVISOR,188708.0,0.0,32080.36,NaN,220788.36,220788.36,2011,NaN,San Francisco,NaN
109,SCOTT SCHOLZEN,FIREFIGHTER,105934.67,96154.33,18655.85,NaN,220744.85,220744.85,2011,NaN,San Francisco,NaN
110,MARK SMITH,ANESTHETIST,206057.69,3431.01,10921.33,NaN,220410.03,220410.03,2011,NaN,San Francisco,NaN
111,C PETRUZZELLA,POLICE OFFICER III,63811.18,57966.33,98578.97,NaN,220356.48,220356.48,2011,NaN,San Francisco,NaN
112,JOHN HALEY JR,DEPUTY DIRECTOR II - MUNICIPAL TRANSPORTATION AG,220115.22,0.0,237.0,NaN,220352.22,220352.22,2011,NaN,San Francisco,NaN
113,NELA PONFERRADA,NURSING SUPERVISOR,188708.0,0.0,31572.3,NaN,220280.30,220280.30,2011,NaN,San Francisco,NaN
114,CHARLES SCOTT,TRANSIT SUPERVISOR,88400.7,119951.72,11893.84,NaN,220246.26,220246.26,2011,NaN,San Francisco,NaN

Replace 'Not Provided' with 0 in BasePay OvertimePay	OtherPay	Benefits #why not get mean rather then get 0

In [26]:
df['BasePay'] = df['BasePay'].replace('Not Provided', 0)
df['OvertimePay'] = df['OvertimePay'].replace('Not Provided', 0)
df['OtherPay'] = df['OtherPay'].replace('Not Provided', 0)
df['Benefits'] = df['Benefits'].replace('Not Provided', 0)
df.iloc[1000:5000].head()

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1000,ROBERT KUZMA,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.84,8577.69,20692.86,NaN,169817.39,169817.39,2011,NaN,San Francisco,NaN
1001,DIANE CARR,NURSE PRACTITIONER,169520.0,0.0,250.0,NaN,169770.00,169770.00,2011,NaN,San Francisco,NaN
1002,SHOTSY FAUST,NURSE PRACTITIONER,169520.0,0.0,250.0,NaN,169770.00,169770.00,2011,NaN,San Francisco,NaN
1003,DIANE KNOLES,ATTORNEY (CIVIL/CRIMINAL),167240.64,0.0,2528.53,NaN,169769.17,169769.17,2011,NaN,San Francisco,NaN
1004,ERIC FLEMING,"HEAD ATTORNEY, CIVIL AND CRIMINAL",169647.29,0.0,0.0,NaN,169647.29,169647.29,2011,NaN,San Francisco,NaN

Change BasePay	OvertimePay	OtherPay	Benefits type to float

In [36]:
df['BasePay'] = df['BasePay'].astype(float)
df['OtherPay'] = df['OtherPay'].astype(float)
df['OvertimePay'] = df['OvertimePay'].astype(float)
df['Benefits'] = df['Benefits'].astype(float)

df['OvertimePay'].dtype

dtype('float64')

Display all employees name and basepay columns who have a BasePay greater than 200,000.

In [41]:
df1 = df[df['BasePay'] > 200000][['EmployeeName' , 'BasePay']]
df1.shape

(509, 2)

Find all employees whose JobTitle contains the word “Manager” (case = False)

In [42]:
df[df.JobTitle.str.contains('Manager',case=False)] #if jobtitle in numeric so what could we do

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
83,EDWARD REISKIN,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,230827.12,0.0,0.00,NaN,230827.12,230827.12,2011,NaN,San Francisco,NaN
87,KEVIN BARRY,MANAGER VII,96814.36,0.0,133563.47,NaN,230377.83,230377.83,2011,NaN,San Francisco,NaN
95,MIVIC HIROSE,MANAGER VIII,215180.76,0.0,12000.00,NaN,227180.76,227180.76,2011,NaN,San Francisco,NaN
162,JULIE LABONTE,MANAGER VIII,207501.20,0.0,2903.37,NaN,210404.57,210404.57,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
147216,Steven D Koneffklatt,Manager III,0.00,0.0,1890.72,342.03,1890.72,2232.75,2014,NaN,San Francisco,PT
147502,Alice B Villagomez,Manager IV,1660.00,0.0,0.00,16.60,1660.00,1676.60,2014,NaN,San Francisco,PT
147805,Stephen C Laplante,Manager II,0.00,0.0,982.62,177.76,982.62,1160.38,2014,NaN,San Francisco,PT
148150,Shirley M Parker,Real Property Manager,0.00,0.0,647.76,0.00,647.76,647.76,2014,NaN,San Francisco,PT
148475,James P Horan,Manager IV,175.75,0.0,0.00,1.41,175.75,177.16,2014,NaN,San Francisco,PT

Retrieve only the columns: EmployeeName, JobTitle, and TotalPay.

In [47]:
df2 = df.loc[:, ['EmployeeName','JobTitle', 'TotalPay']]
df2.head()

,EmployeeName,JobTitle,TotalPay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19

Find count of employees who have zero OvertimePay.

In [52]:
df2 = (df['OvertimePay'] == 0).sum()
print(df2)
df3 = df[df['OvertimePay'] == 0][['OvertimePay' , 'BasePay']]
df3.head()

77321

    OvertimePay    BasePay
0           0.0  167411.18
7           0.0  256576.96
9           0.0  285262.00
12          0.0  294580.02
13          0.0  271329.03

Calculate the TotalPay for each JobTitle where totalpay > 300000

In [58]:
df4 = (df[df['TotalPay'] > 300000 ].groupby('JobTitle')['TotalPay'].sum())
df4.head((20))

JobTitle
ASSISTANT DEPUTY CHIEF II                        316285.74
Assistant Deputy Chief 2                         654066.15
Asst Chf of Dept (Fire Dept)                    1303828.26
Asst Med Examiner                               1069837.40
BATTALION CHIEF, (FIRE DEPARTMENT)               619408.60
Battalion Chief, Fire Suppress                  2845960.11
Battlion Chief, Fire Suppressi                  1266054.40
CAPTAIN III (POLICE DEPARTMENT)                  874189.19
CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)           302377.73
Captain 3                                       1274613.48
Captain, Fire Suppression                        610671.88
Chief Investment Officer                         339653.70
Chief of Police                                  987550.94
Chief, Fire Department                           977915.05
Commander 3                                      322143.10
DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)     326373.19
DEPUTY DIRECTOR OF INVESTMENTS                   307899.46
Dep Dir for Investments, Ret                     315572.01
Dept Head V                                      927825.30
Deputy Chief 3                                   471952.64
Name: TotalPay, dtype: float64

Find the top 5 JobTitles with the highest average TotalPayBenefits show in descending order

In [59]:
grouped = df.groupby('JobTitle')['TotalPayBenefits']
avg = grouped.mean()
s_avg = avg.sort_values(ascending=False)
s_avg.head(5)

JobTitle
Chief Investment Officer                          436224.360000
Chief of Police                                   411732.266667
Chief, Fire Department                            408865.326667
GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY    399211.275000
Gen Mgr, Public Trnsp Dept                        380696.440000
Name: TotalPayBenefits, dtype: float64

Replace all missing Benefits values with 0

In [62]:
df['Benefits'].isnull().sum()

np.int64(36159)

In [68]:
df['Benefits'] = df['Benefits'].fillna(0)
df['Benefits'].isnull().sum()
df.iloc[147216:147250]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
147216,Steven D Koneffklatt,Manager III,0.00,0.00,1890.72,342.03,1890.72,2232.75,2014,NaN,San Francisco,PT
147217,William D Cahill,Physician Specialist,1832.40,0.00,0.00,398.59,1832.40,2230.99,2014,NaN,San Francisco,PT
147218,Gabriela Cardona,Architectural Assistant 2,1838.90,0.00,0.00,391.63,1838.90,2230.53,2014,NaN,San Francisco,PT
147219,Donna A Chardon,Special Nurse,1525.40,0.00,287.71,413.79,1813.11,2226.90,2014,NaN,San Francisco,PT
147220,Racquel M Mcgee,Communications Dispatcher 1,2051.47,52.90,99.70,22.04,2204.07,2226.11,2014,NaN,San Francisco,PT
147221,Xanthy S Michealsen,Special Nurse,1744.50,0.00,56.64,423.65,1801.14,2224.79,2014,NaN,San Francisco,PT
147222,Salvador Vasquez,Swimming Instructor,2197.01,0.00,4.67,22.02,2201.68,2223.70,2014,NaN,San Francisco,PT
147223,Aaron M Kingon,Junior Clerk,1467.19,733.60,0.00,22.01,2200.79,2222.80,2014,NaN,San Francisco,PT
147224,Karina E Klein,Special Nurse,1749.90,0.00,58.33,414.51,1808.23,2222.74,2014,NaN,San Francisco,PT
147225,Kristine N Leffers,Commissioner No Benefits,2200.00,0.00,0.00,22.00,2200.00,2222.00,2014,NaN,San Francisco,PT
147226,Ranita R Novak,Special Nurse,1625.05,0.00,196.80,398.57,1821.85,2220.42,2014,NaN,San Francisco,PT
147227,Vincent Nguyen,Publ Svc Aide-Asst to Prof,2197.91,0.00,0.00,21.98,2197.91,2219.89,2014,NaN,San Francisco,PT
147228,Lisa M. Pham,PS Aide Health Services,2187.88,0.00,0.00,21.88,2187.88,2209.76,2014,NaN,San Francisco,PT
147229,Silvia R Tacuri,Licensed Vocational Nurse,1796.05,0.00,9.60,403.02,1805.65,2208.67,2014,NaN,San Francisco,PT
147230,Preeya K Maan,Recreation Leader,2151.53,0.00,34.60,21.86,2186.13,2207.99,2014,NaN,San Francisco,PT
147231,Daniel Goodman,Junior Clerk,1584.56,601.55,0.00,21.86,2186.11,2207.97,2014,NaN,San Francisco,PT
147232,Donald A Brown,Junior Clerk,1461.50,724.31,0.00,21.86,2185.81,2207.67,2014,NaN,San Francisco,PT
147233,Jesse R White,Public Svc Aide-Public Works,2183.34,0.00,0.00,21.84,2183.34,2205.18,2014,NaN,San Francisco,PT
147234,Maria R Verlanic,Senior Clerk,2181.80,0.00,0.00,21.82,2181.80,2203.62,2014,NaN,San Francisco,PT
147235,Celestine Dixon,Health Care Billing Clerk 2,1163.20,0.00,542.11,490.24,1705.31,2195.55,2014,NaN,San Francisco,PT
147236,Celeste R Walley,Publ Svc Aide-Asst to Prof,2173.11,0.00,0.00,21.73,2173.11,2194.84,2014,NaN,San Francisco,PT
147237,Katrina A Meier,Special Nurse,1751.40,0.00,58.38,385.04,1809.78,2194.82,2014,NaN,San Francisco,PT
147238,David A Aaron,Public Svc Aide-Public Works,2119.94,0.00,47.65,21.68,2167.59,2189.27,2014,NaN,San Francisco,PT
147239,Arthur B Chaney,Child Support Officer II,0.00,0.00,2188.93,0.00,2188.93,2188.93,2014,NaN,San Francisco,PT
147240,Venus A Naldoza`,Patient Care Assistant,2107.20,0.00,56.20,21.63,2163.40,2185.03,2014,NaN,San Francisco,PT
147241,Isaac A Maycock,Camp Assistant,2127.79,0.00,32.21,21.59,2160.00,2181.59,2014,NaN,San Francisco,PT
147242,Courtney A Young,Recreation Leader,2159.82,0.00,0.00,21.61,2159.82,2181.43,2014,NaN,San Francisco,PT
147243,Daniel D Rhodes,Public Svc Aide-Public Works,1951.41,167.18,37.06,21.55,2155.65,2177.20,2014,NaN,San Francisco,PT
147244,Kenny Young,Junior Clerk,1634.00,520.13,0.00,21.54,2154.13,2175.67,2014,NaN,San Francisco,PT
147245,Bridget K Conaway,Public Service Trainee,2153.37,0.00,0.00,21.53,2153.37,2174.90,2014,NaN,San Francisco,PT
147246,Vitaliy Vernikov,Junior Clerk,1368.00,783.75,0.00,21.52,2151.75,2173.27,2014,NaN,San Francisco,PT
147247,Calvin Chin Hung Luo,Pool Lifeguard,2095.68,0.00,54.54,21.52,2150.22,2171.74,2014,NaN,San Francisco,PT
147248,Annika W Ehrlich,Nurse Practitioner,2149.60,0.00,0.00,21.50,2149.60,2171.10,2014,NaN,San Francisco,PT
147249,William L Walker,"StdntDsgnTrain1, Arch/Eng/Plng",2144.52,0.00,0.00,21.46,2144.52,2165.98,2014,NaN,San Francisco,PT

Identify the top employee name by TotalPay in each Year. Show year, employeename and totalpay dataframe

In [69]:
idx = df.groupby('Year')['TotalPay'].idxmax()
df.loc[idx, ['Year','EmployeeName','TotalPay']]

        Year    EmployeeName   TotalPay
0       2011  NATHANIEL FORD  567595.43
36159   2012  Gary Altenberg  362844.66
72927   2013     Samson  Lai  347102.32
110531  2014     David Shinn  471952.64

Find the number of employees per JobTitle.

In [73]:
df7 = df.groupby('JobTitle')['EmployeeName'].count()
df7.head(50)

JobTitle
ACCOUNT CLERK                                          83
ACCOUNTANT                                              5
ACCOUNTANT INTERN                                      48
ACPO,JuvP, Juv Prob (SFERS)                             1
ACUPUNCTURIST                                           1
ADMINISTRATIVE ANALYST                                 93
ADMINISTRATIVE ANALYST II                               2
ADMINISTRATIVE ANALYST III                              2
ADMINISTRATIVE ENGINEER                                10
ADMINISTRATIVE SERVICES MANAGER                         3
ADMINISTRATOR, SFGH MEDICAL CENTER                      1
AFFIRMATIVE ACTION SPECIALIST                           6
AGRICULTURAL INSPECTOR                                  2
AIRPORT ASSISTANT DEPUTY DIRECTOR, BUSINESS ADMINI      1
AIRPORT ASSISTANT DEPUTY DIRECTOR, OPERATIONS           1
AIRPORT COMMUNICATIONS OPERATOR                        27
AIRPORT COMMUNICATIONS SUPERVISOR                       2
AIRPORT ECONOMIC PLANNER                               13
AIRPORT ELECTRICIAN                                    17
AIRPORT ELECTRICIAN SUPERVISOR                          2
AIRPORT EMERGENCY PLANNING COORDINATOR                  2
AIRPORT MECHANICAL MAINTENANCE SUPERVISOR               1
AIRPORT NOISE ABATEMENT SPECIALIST                      2
AIRPORT OPERATIONS SUPERVISOR                          12
AIRPORT POLICE SERVICES AIDE                          187
AIRPORT PROPERTY SPECIALIST I                          13
AIRPORT SAFETY OFFICER                                 40
ANESTHETIST                                            25
ANIMAL CARE ASSISTANT SUPERVISOR                        1
ANIMAL CARE ATTENDANT                                  14
ANIMAL CARE SUPERVISOR                                  1
ANIMAL CONTROL OFFICER                                 13
ANIMAL HEALTH TECHNICIAN                                3
ANIMAL KEEPER                                           4
APPRENTICE GARDENER                                    11
APPRENTICE STATIONARY ENGINEER                         12
APPRENTICE STATIONARY ENGINEER, SEWAGE PLANT           13
APPRENTICE STATIONARY ENGINEER,WATER TREATMENT PLN      6
ARCHITECT                                              15
ARCHITECTURAL ADMINISTRATOR                             4
ARCHITECTURAL ASSISTANT  I                              2
ARCHITECTURAL ASSISTANT II                             19
ARCHITECTURAL ASSOCIATE  I                             13
ARCHITECTURAL ASSOCIATE II                             20
AREA SUPERVISOR, PARKS, SQUARES AND FACILITIES          1
ARTS PROGRAM ASSISTANT                                 11
ASPHALT FINISHER                                       10
ASPHALT FINISHER SUPERVISOR I                           8
ASPHALT PLANT SUPERVISOR I                              1
ASPHALT WORKER                                         26
Name: EmployeeName, dtype: int64

In [ ]:
top_10_jobs = df.groupby('JobTitle').size().sort_values(ascending=False).head(10)
print(top_10_jobs)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Custodian                       2418
TRANSIT OPERATOR                2388
Firefighter                     2359
Recreation Leader               1971
Patient Care Assistant          1945
dtype: int64